# Generated by Django 6.0.5 on 2026-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
