# Generated by Django 6.0.5 on 2026-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_blog_facebook_link_blog_tiktok_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'YouTube Video')], default='image', max_length=20),
        ),
    ]
