# Generated by Django 6.0.5 on 2026-06-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_blog_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_per_question',
            field=models.PositiveIntegerField(blank=True, help_text='Time per question in seconds', null=True),
        ),
    ]
