# Generated by Django 6.0.5 on 2026-05-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=150)),
                ('quiz_name', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField(default=0)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
