# Generated by Django 6.0.5 on 2026-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
