# Generated by Django 6.0.5 on 2026-06-28 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Appliance Name')),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('industrial', 'Industrial')], default='residential', max_length=20)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fa-wind)', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text='e.g., 1 Ton, 1.5 Ton, 1 HP, 20 Watt', max_length=100)),
                ('default_watt', models.PositiveIntegerField(help_text='Default power consumption in Watts')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='solar_designer.appliance')),
            ],
        ),
    ]
