# Generated by Django 6.0.5 on 2026-06-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_designer', '0002_appliance_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='appliance',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/icons/', verbose_name='Upload Icon Image'),
        ),
    ]
