# Generated by Django 6.0.5 on 2026-06-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_designer', '0003_remove_appliance_icon_class_appliance_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='is_default',
        ),
        migrations.AddField(
            model_name='appliancevariant',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Show this Variant as Default'),
        ),
    ]
