# Generated by Django 6.0.5 on 2026-07-06 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_designer', '0004_remove_appliance_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name (যেমন: লাইট, ফ্যান)')),
                ('slug', models.SlugField(help_text='ইংরেজিতে ইউনিক কোড (যেমন: lighting, fan, ac)', max_length=100, unique=True)),
                ('icon_emoji', models.CharField(default='🔌', help_text='UI এর জন্য একটি ইমোজি দিন (যেমন: 💡, 🌀, ❄️)', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='appliancevariant',
            name='default_hours',
            field=models.FloatField(default=6.0, help_text='দৈনিক ডিফল্ট ব্যবহারের সময় (ঘণ্টায়), যেমন: 6, 4.5'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Appliance Name (যেমন: LED Bulb, Ceiling Fan)'),
        ),
        migrations.AlterField(
            model_name='appliancevariant',
            name='variant_name',
            field=models.CharField(help_text='e.g., 1 Ton, 1.5 Ton, 9 Watt', max_length=100),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='solar_designer.appliancecategory'),
        ),
    ]
