# Generated by Django 6.0.5 on 2026-07-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_designer', '0005_appliancecategory_appliancevariant_default_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliancecategory',
            options={'verbose_name': 'Appliance Category', 'verbose_name_plural': 'Appliance Categories'},
        ),
        migrations.RemoveField(
            model_name='appliancecategory',
            name='icon_emoji',
        ),
        migrations.AddField(
            model_name='appliancecategory',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Icon Image'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Appliance Name (e.g., LED Bulb, Ceiling Fan)'),
        ),
        migrations.AlterField(
            model_name='appliancecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='appliancecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='appliancevariant',
            name='default_hours',
            field=models.FloatField(default=6.0, help_text='Default daily usage time in hours, e.g., 6.0, 4.5'),
        ),
    ]
